server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: bios4u
    url: jdbc:mysql://oban.erasmusmc.nl:3306/clinicaltrials180619?useSSL=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: biosemantics
    hikari:
            idle-timeout: 10000
            maximumPoolSize: 30
  mvc:
    log-resolved-exception: true

logging:
  file: clinicaltrials-pa.log
