apiVersion: v1
kind: Service
metadata:
  name: clinicalpa 
  namespace: kh
  labels:
    app: clinicalpa
  annotations:
    etransafe.eu/base.url: /clinicaltrials-pa/v1
spec:
  type: ClusterIP # during the development, LoadBalancer can be used to test the service. In production, only ClusterIP should be used here.
  ports:
  - port: 52149
  selector:
    app: clinicalpa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinicalpa
  namespace: kh
  labels:
    app: clinicalpa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clinicalpa
  template:
    metadata:
      labels:
        app: clinicalpa
    spec:
      serviceAccountName: etransafe
      containers:
      - name: clinicalpa
        image: dockerhub.etransafe.eu:5111/wp9/emc/clinicaltrials-pa:latest
        imagePullPolicy: Always # :latest tag already ensures updates when a new image is there
        ports:
        - containerPort: 18999
        env:
          - name: CLINICALPA_SERVICE_LOGIN
            valueFrom:
              secretKeyRef:
                name: clinicalpa-etransafe-cred
                key: CLINICALPA_SERVICE_LOGIN
          - name: CLINICALPA_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: clinicalpa-etransafe-cred
                key: CLINICALPA_SERVICE_PASSWORD
        livenessProbe:
          httpGet:
            path: /api/clinicaltrials-pa/v1/alive
            port: 52149
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /api/clinicaltrials-pa/v1/ready
            port: 52149
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 10
      imagePullSecrets:
      - name: dockerhub-etransafe-regcred
---
# Ambassador route for the service
apiVersion: v1
kind: Service
metadata:
  name: clinicalpa-route
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  clinicalpa-mapping
      prefix: /clinicalpa.kh.svc/
      service: clinicalpa.kh.svc:52149
      host_rewrite: clinicalpa.kh.svc
spec:
  ports:
  - name: clinicalpa-port
    port: 52149
